name: Lighthouse Check
on: [push]
jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: ./
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://www.foo.software'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
