name: Test Overrides
on: [push]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Lighthouse
      uses: ./
      with:
        overridesJsonFile: '.github/workflows/overrides.json'
        urls: 'https://www.foo.software'
